### ISSUE TITLE
Divisão dos temas.

### ISSUE THREAD

**Issue by Kertf22** [Kertf22/POO_projeto#1]
1 - Usuário

2 - Item, livro, monografia e periódico.

3 - Classes auxiliares ex: Data,  Emprestimo, Reserva 

4 - Biblioteca e main. 

Alguns vão falar mais que outros mas faz parte.

Cada um escolhe ai e respondendo aqui.

**Comment by treepo1** [comment]
4

**Comment by Gbishoppp** [comment]
1

**Comment by DaniloResende** [comment]
3

**Comment by Kertf22** [comment]
Então eu fico com 2.
